export const MOCK_WASTES = [
  {
    id: 1,
    material: "escombros",
    description: "Escombros de demolición mixtos",
    quantity: 12,
    unit: "m³",
    address: "Av. Principal 123, Santiago",
    status: "publicado",
    createdAt: "2026-09-01",
    matches: 3,
  },
  {
    id: 2,
    material: "madera",
    description: "Palets de madera en buen estado",
    quantity: 50,
    unit: "kg",
    address: "Calle Industrial 45, Maipú",
    status: "matcheado",
    createdAt: "2026-09-02",
    matches: 5,
  },
  {
    id: 3,
    material: "metal",
    description: "Chapas de acero galvanizado",
    quantity: 200,
    unit: "kg",
    address: "Pasaje Comercio 8, Providencia",
    status: "agendado",
    createdAt: "2026-09-02",
    matches: 2,
  },
  {
    id: 4,
    material: "plastico",
    description: "Botellas PET clasificadas",
    quantity: 30,
    unit: "kg",
    address: "Av. Las Torres 99, La Florida",
    status: "completado",
    createdAt: "2026-08-28",
    matches: 4,
  },
  {
    id: 5,
    material: "carton",
    description: "Cajas de cartón aplastadas",
    quantity: 80,
    unit: "kg",
    address: "Ruta 68 km 15, Quilicura",
    status: "publicado",
    createdAt: "2026-09-03",
    matches: 1,
  },
];

export const MOCK_STATS = {
  published: 2,
  matched: 1,
  scheduled: 1,
  completed: 1,
  totalKg: 360,
  totalM3: 12,
  co2Saved: 145,
  activeMatches: 15,
};

export const MOCK_MONTHLY_DATA = [
  { month: "Abr", value: 40 },
  { month: "May", value: 65 },
  { month: "Jun", value: 50 },
  { month: "Jul", value: 80 },
  { month: "Ago", value: 95 },
  { month: "Sep", value: 110 },
];
