export const MOCK_USERS = [
  {
    id: 1,
    fullName: "María González",
    email: "maria.gonzalez@email.com",
    role: "donador",
    address: "Av. Las Flores 123, Santiago",
    phone: "+56 9 1234 5678",
    status: "activo",
    createdAt: "2026-09-01",
    wastesPublished: 5,
    totalKg: 120,
  },
  {
    id: 2,
    fullName: "Fundación Recicla",
    email: "contacto@fundacionrecicla.org",
    role: "ong",
    address: "Calle Comunitaria 45, Maipú",
    phone: "+56 9 8765 4321",
    status: "activo",
    createdAt: "2026-09-01",
    wastesPublished: 0,
    totalKg: 340,
  },
  {
    id: 3,
    fullName: "Transportes EcoLogística",
    email: "ops@ecologistica.cl",
    role: "transportista",
    address: "Polígono Industrial 7, Quilicura",
    phone: "+56 9 5555 1234",
    status: "activo",
    createdAt: "2026-09-02",
    wastesPublished: 0,
    totalKg: 0,
  },
  {
    id: 4,
    fullName: "Carlos Pérez",
    email: "carlos.perez@email.com",
    role: "donador",
    address: "Pasaje del Sol 88, La Florida",
    phone: "+56 9 2222 3333",
    status: "activo",
    createdAt: "2026-09-02",
    wastesPublished: 3,
    totalKg: 75,
  },
  {
    id: 5,
    fullName: "Taller Manos Verdes",
    email: "taller@manosverdes.org",
    role: "ong",
    address: "Av. Artesanal 12, Providencia",
    phone: "+56 9 4444 5555",
    status: "pendiente",
    createdAt: "2026-09-03",
    wastesPublished: 0,
    totalKg: 0,
  },
  {
    id: 6,
    fullName: "Juan Rojas",
    email: "juan.rojas@email.com",
    role: "donador",
    address: "Calle Nueva 200, Ñuñoa",
    phone: null,
    status: "activo",
    createdAt: "2026-09-03",
    wastesPublished: 2,
    totalKg: 40,
  },
  {
    id: 7,
    fullName: "EcoMudanzas SpA",
    email: "admin@ecomudanzas.cl",
    role: "transportista",
    address: "Ruta 68 km 15, Quilicura",
    phone: "+56 9 7777 8888",
    status: "suspendido",
    createdAt: "2026-08-30",
    wastesPublished: 0,
    totalKg: 0,
  },
];

export const MOCK_ADMIN_STATS = {
  totalUsers: 7,
  donadores: 3,
  ongs: 2,
  transportistas: 2,
  totalWastes: 10,
  totalKg: 575,
  activeMatches: 15,
  completedTransfers: 8,
  pendingApprovals: 1,
};
